# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

gems:
  - jekyll-assets

assets:
  features:
    liquid: false
  assets:
    - "*.png"
    - "main.css"
  sources:
    - bower_components
    - img

# Site settings
title: DanceSocially
email: georg@get83.de
description: >
  DanceSocially ist die Webseite des Tanztrainers Georg Tavonius mit Informationen
  zum Thema West Coast Swing und Gesellschaftstanzen. Hier erfahrt ihr, wo es Kurse
  oder die nächste Veranstaltung gibt. In Hamburg und in Deutschland.
keywords: >
  West Coast Swing, Hamburg, WCS, tanzen, WCS Unterricht, West Coast Swing lernen,
  West Coast Swing Events, West Coast Swing Workshops, WCS Events, WCS Workshops,
  Was ist West Coast Swing
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.dancesocially.com" # the base hostname & protocol for your site
twitter_username: Georg_Tavonius
github_username: Calamari
googleplus_url: https://plus.google.com/u/0/100254305021076830105

og_description: West Coast Swing in Hamburg mit Georg Tavonius. Blog, Infos und mehr.

# Facebook app id, so we can clear cache and stuff
fb:
  app_id: 1111600618858744,

menu_entries:
  # -
  #   title: Blog
  #   url: /
  - title: Über mich
    url: /ueber-mich/
  - title: West Coast Swing
    sub_menu:
      - title: Was ist West Coast Swing
        url: /west-coast-swing/
      - title: West Coast Swing Unterricht in Hamburg
        url: /wcs-unterricht/
      - title: Events und Workshops
        url: /events-workshops/
  - title: Zouk
    sub_menu:
      - title: Was ist Zouk
        url: /zouk/
      - title: Zouk Unterricht in Hamburg
        url: /zouk-unterricht/
      - title: Events und Workshops
        url: /zouk-events-workshops/

# Build settings
markdown: kramdown

# event_promo:
#   date: 2016-04-30T10:30+01:00
#   endDate: 2016-05-01T18:00+01:00
#   title: WCS-Intensive mit Eric Jacobson 2016
#   image: www.dancesocially.com/assets/fb-eric-intensive-2.jpg
#   url: www.dancesocially.com/events/eric-intensive-2016/
#   description: Der AllStar Eric Jacobson ist wieder zu Besuch in Hamburg. Für ein weiteres hochklassiges Intensiv-Workshop.
#   location:
#     name: Tanzschule Heiko Stender
#     address: Tibarg 40, 22459 Hamburg
#     url: www.tanzschule-stender.de
#   offers:
#     -
#       name: Anmeldung im Februar
#       price: 110
#     -
#       name: Anmeldung im März
#       price: 120
#     -
#       name: Anmeldung im April
#       price: 130
#   performer:
#     name: Eric B. Jacobson
#     url: www.nakedbasics.com

# event_promo:
#   date: 2018-01-11T19:00+01:00
#   endDate: 2018-03-29T20:15+01:00
#   title: Neuer Zouk Anfängerkurs ab Januar
#   image: scontent-amt2-1.xx.fbcdn.net/v/t1.0-9/23621209_904086379748779_212739750796672992_n.jpg
#   url: www.facebook.com/events/1778822458795270/
#   description: Ab Januar gibt es eine neue Gelegenheit diesen sinnlichen und vielseitigen Tanz in Hamburg zu erlernen.
#   location:
#     name: Gymnastica Hamburg
#     address: Eilbeker Weg 90, 22089 Hamburg
#     url: www.zouk-hh.de
#   performer:
#     name: Zouk-HH
#     url: www.zouk-hh.de

wcs_parties:
  # -
  #   date: 2017-09-02
  #   title: Anchor Saturday
  #   url: www.facebook.com/events/229807244169983
  #   location:
  #     name: Isabel Edvardsson - Die Tanzschule
  #     address: Banksstr. 2b, 20097 Hamburg
  #     url: www.facebook.com/Isabel-Edvardsson-DIE-Tanzschule-725862844157068/
  # -
  #   date: 2017-09-15
  #   title: West Coast Friday
  #   url: www.facebook.com/events/1863905547159981
  #   location:
  #     name: Isabel Edvardsson - Die Tanzschule
  #     address: Banksstr. 2b, 20097 Hamburg
  #     url: www.facebook.com/Isabel-Edvardsson-DIE-Tanzschule-725862844157068/
  # -
  #   date: 2017-10-21
  #   title: Uni Danza
  #   url: www.unidanza.de
  #   location:
  #     name: ETV Hamburg
  #     address: Bundesstr. 96, 20144 Hamburg
  #     url: web.etv.hamburg
  # -
  #   date: 2017-11-17
  #   title: West Coast Friday
  #   url: www.julianundjuliane.de/termine/west-coast-swing-partys/
  #   location:
  #     name: Isabel Edvardsson - Die Tanzschule
  #     address: Banksstr. 2b, 20097 Hamburg
  #     url: www.facebook.com/Isabel-Edvardsson-DIE-Tanzschule-725862844157068/
  # -
  #   date: 2017-12-15
  #   title: West Coast Friday
  #   url: www.julianundjuliane.de/termine/west-coast-swing-partys/
  #   location:
  #     name: Isabel Edvardsson - Die Tanzschule
  #     address: Banksstr. 2b, 20097 Hamburg
  #     url: www.facebook.com/Isabel-Edvardsson-DIE-Tanzschule-725862844157068/
  # -
  #   date: 2018-01-06
  #   title: Anchor Saturday
  #   url: www.julianundjuliane.de/termine/west-coast-swing-partys/
  #   location:
  #     name: Isabel Edvardsson - Die Tanzschule
  #     address: Banksstr. 2b, 20097 Hamburg
  #     url: www.facebook.com/Isabel-Edvardsson-DIE-Tanzschule-725862844157068/
  # -
  #   date: 2018-02-03
  #   title: Anchor Saturday
  #   url: www.julianundjuliane.de/termine/west-coast-swing-partys/
  #   location:
  #     name: Isabel Edvardsson - Die Tanzschule
  #     address: Banksstr. 2b, 20097 Hamburg
  #     url: www.facebook.com/Isabel-Edvardsson-DIE-Tanzschule-725862844157068/
  # -
  #   date: 2018-03-03
  #   title: Anchor Saturday
  #   url: www.julianundjuliane.de/termine/west-coast-swing-partys/
  #   location:
  #     name: Isabel Edvardsson - Die Tanzschule
  #     address: Banksstr. 2b, 20097 Hamburg
  #     url: www.facebook.com/Isabel-Edvardsson-DIE-Tanzschule-725862844157068/
  # -
  #   date: 2018-03-16
  #   title: West Coast Friday
  #   url: www.julianundjuliane.de/termine/west-coast-swing-partys/
  #   location:
  #     name: Isabel Edvardsson - Die Tanzschule
  #     address: Banksstr. 2b, 20097 Hamburg
  #     url: www.facebook.com/Isabel-Edvardsson-DIE-Tanzschule-725862844157068/
  # - date: 2018-04-30
  #   title: West Coast Swing in den Mai
  #   url: www.facebook.com/events/814256315425354
  #   location:
  #     name: Billies - Das Tanzstudio
  #     address: Stresemannstraße 374, 22761 Hamburg
  #     url: www.billies.de

wcs_workshops:
  # -
  #   date: 2017-10-26
  #   endDate: 2017-10-30
  #   title: Warsaw Halloween Swing
  #   url: warsawhalloweenswing.com
  #   description: Gruseliges WSDC-Registry und Tanz-Event. Es besticht durch eine tolle Atmosphäre, sensationelle Kostüme und gute Workshops.
  #   location:
  #     name: The WESTIN Warsaw
  #     address: Jana Pawla II 21, 00-854 Warsaw, Poland
  #     url: www.facebook.com/the.westin.warsaw
  # -
  #   date: 2017-11-10
  #   endDate: 2017-11-12
  #   title: Red Light Swing
  #   url: www.redlightswing.com
  #   description: Hamburgs neustes West Coast Swing Event.
  # -
  #   date: 2017-12-16
  #   endDate: 2017-12-17
  #   title: Nordic X-Mas Swing
  #   url: www.facebook.com/events/640325396155700
  #   description: Norddeutsche Trainer in einem Weichnachtlichen Event
  #   location:
  #     name: Tanzfabrik Ahrensburg
  #     address: Am Alten Markt 14, 22926 Ahrensburg
  #     url: www.tanzfabrik-ahrensburg.de
  # -
  #   date: 2018-03-28
  #   endDate: 2018-04-02
  #   title: Anchor Festival
  #   url: www.anchor-festival.com
  #   description: West Coast Swing meets Waterkant. Das erste große West Coast Swing Festival im Norden.
  #   location:
  #     name: Mozartsäle
  #     address: Moorweidenstraße 36, 20146 Hamburg
  #     url: www.mozart-saele.de
  # -
  #   date: 2018-05-05
  #   endDate: 2018-05-05
  #   title: "Workshoptag mit Evgenia ‘Evi‘ Itkina"
  #   url: www.facebook.com/events/551777521831388/
  #   description: Ein Tag voller Workshopds mit der talentierten und großartigen Tänzerin Evi.
  #   location:
  #     name: Tanzen in Kiel - Tanzsportzentrum
  #     address: Suchskrug 1, 24107 Kiel
  - date: 2019-11-30
    endDate: 2019-12-01
    title: Nordic X-Mas Swing
    url: www.facebook.com/events/367847234093956/
    description: Norddeutsche Trainer in einem Weichnachtlichen Event
    location:
      name: Tanzfabrik Ahrensburg
      address: Am Alten Markt 14, 22926 Ahrensburg
      url: www.tanzfabrik-ahrensburg.de

zouk_parties:
  # -
  #   date: 2017-09-24
  #   title: Sunday to Flow
  #   url: www.facebook.com/events/1878236225829213
  #   location:
  #     name: Zouk-HH Raum
  #     address: Wandsbeker Chausse 62A, 22089 Hamburg
  # -
  #   date: 2017-10-07
  #   title: Go with the Flow
  #   url: www.facebook.com/events/1876698339257330
  #   location:
  #     name: TanzCentrum Gold und Silber Bremen e.V.
  #     address: Waller Heerstraße 46, 28217 Bremen, Germany
  #     url: tc-gold-und-silber.de
  # -
  #   date: 2017-11-29
  #   title: Sunday to Flow
  #   url: www.zouk-hh.de
  #   location:
  #     name: Zouk-HH Raum
  #     address: Wandsbeker Chausse 62A, 22089 Hamburg
  # -
  #   date: 2017-12-09
  #   title: Go with the Flow mit Junior
  #   url: www.facebook.com/events/452687155097728
  #   location:
  #     name: TanzCentrum Gold und Silber Bremen e.V.
  #     address: Waller Heerstraße 46, 28217 Bremen, Germany
  #     url: tc-gold-und-silber.de
  # - date: 2018-04-08
  #   title: Sunday to Flow
  #   url: www.facebook.com/events/573012466409750/
  #   location:
  #     name: Zouk-HH Raum
  #     address: Wandsbeker Chausse 62A, 22089 Hamburg
  # - date: 2018-04-14
  #   title: Go with the Flow
  #   url: www.facebook.com/events/2031574310416283/
  #   location:
  #     name: TanzCentrum Gold und Silber Bremen e.V.
  #     address: Waller Heerstraße 46, 28217 Bremen, Germany
  #     url: tc-gold-und-silber.de
  # - date: 2018-05-12
  #   title: Go with the Flow
  #   url: www.facebook.com/events/161102451261330/
  #   location:
  #     name: TanzCentrum Gold und Silber Bremen e.V.
  #     address: Waller Heerstraße 46, 28217 Bremen, Germany
  #     url: tc-gold-und-silber.de
  - date: 2019-11-03
    title: Sunday to Flow
    url: www.facebook.com/events/573012466409750/
    location:
      name: Zouk-HH Raum
      address: Wandsbeker Chausse 62A, 22089 Hamburg

zouk_workshops:
  # -
  #   date: 2017-09-28
  #   endDate: 2017-10-01
  #   title: 4. Zouk/Kizomba Gala in Hannover
  #   url: www.facebook.com/events/1792200144369871/
  #   description: Ein Zouk und Kizomba Mix-Event im Norden Deutschlands. Die Hamburger werden da zahlreich vertreten sein.
  #   location:
  #     name: Culinar Hannover
  #     address: Am Grossen Garten 3, 30419 Hannover
  #     url: www.salsa-culinar.de
  # -
  #   date: 2017-12-08
  #   endDate: 2017-12-10
  #   title: Zouk Family Meeting christmas edition
  #   url: zouk-dresden.de/?q=zfm13
  #   description: Die Weihnachtsausgabe eines sehr schönes und familiäres Zouk Event in Dresen. Natürlich mit gemeinsamen Weihnachtsmarktbesuch!
  #   location:
  #     name: dance studio “Sandana”
  #     address: Trachenberger Platz 3, 01139 Dresden
  #     url: www.salsa-sandana.de/startseite/
  # -
  #   date: 2017-12-29
  #   endDate: 2018-01-01
  #   title: Zouk New Year's Eve Erfurt 2017/2018
  #   url: www.zouk-thueringen.de/new-years-eve-party-2017-2018/
  #   description: Die beste Art tänzerisch ins neue Jahr zu Feiern. 3 Tage lang Zouk Workshops und Tanzen.
  #   location:
  #     name: Erfurt
  #     address: Erfurt
  #     url: www.zouk-thueringen.de/new-years-eve-party-2017-2018/venue-and-location/
  # -
  #   date: 2018-03-16
  #   endDate: 2018-03-18
  #   title: Soulzouk Weekend Nummber 2
  #   url: www.facebook.com/events/811088739077732/
  #   description: Ein Zoukwochende in Bonn mit Bruno Galhardo.
  #   location:
  #     name: Bonn
  #     address: Bonn
  #     url: zoukernatural.de/index.php/soulzouk-weekend-nummer-2/
  - date: 2019-12-29
    endDate: 2020-01-01
    title: Zouk New Year's Eve Erfurt 2019/2020
    url: www.zouk-thueringen.de/new-years-eve-party-2019-2020
    description: Die beste Art tänzerisch ins neue Jahr zu Feiern. 3 Tage lang Zouk Workshops und Tanzen.
    location:
      name: Erfurt
      address: Erfurt
      url: www.zouk-thueringen.de/new-years-eve-party-2019-2020/venue-and-location/

zouk_workshops_suggestions:
  # - date: 2018-04-06
  #   endDate: 2018-04-08
  #   title: "Zoukstyles: Bruno Galhardo Weekend"
  #   url: www.facebook.com/events/140894306587040/
  #   description: Ein Zoukwochende in Bonn mit Bruno Galhardo.
  #   location:
  #     name: Bonn
  #     address: Bonn
  #     url: zoukernatural.de/index.php/zoukstyles-bruno-galhardo-weekend/
  # - date: 2018-06-07
  #   endDate: 2018-06-14
  #   title: "ZOUKTIME! summer zouk paradise in Croatia 2018"
  #   url: www.facebook.com/events/136952243683303/
  #   description: Eine Woche Zouk an der Sonne.
  #   location:
  #     name: Luna Island Hotel
  #     address: JAKISNICA BB, 53294 Lun, Primorsko-Goranska, Croatia

wcs_workshops_suggestions:
  # -
  #   date: 2017-12-07
  #   endDate: 2017-12-10
  #   title: Berlin Swing Revolution
  #   url: berlinswingrevolution.de/
  #   description: Die Berlin Swing Revolution geht in die zweite Runde. Diesmal als WSDC-Registry Event.
  #   location:
  #     name: ??
  #     address: ??
  #     url: berlinswingrevolution.de/
  # -
  #   date: 2018-03-26
  #   endDate: 2018-03-29
  #   title: West Coast Spring
  #   url: www.westcoastspring.de/
  #   description: Ein reines West Coast Swing Social Festival mit tollen Trainern.
  #   location:
  #     name: Kurhaus Bad Krozingen
  #     address: Kurhausstraße 1, 79189 Bad Krozingen
  #     url: www.kurpark-catering.de/startseite/
  # - date: 2018-05-18
  #   endDate: 2018-05-21
  #   title: "Swingmany"
  #   url: www.facebook.com/events/1662561053805308/
  #   description: Die deutsche Pflichtveranstaltung zu Pfingsten.
  #   location:
  #     name: Taktgefühl
  #     address: Edouard-Desor-Strasse 2, 61381 Friedrichsdorf
