# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

gems:
- jekyll-assets

assets:
  features:
    liquid: false
  assets:
    - "*.png"
    - "main.css"
  sources:
    - bower_components
    - img

# Site settings
title: DanceSocially
email: georg@get83.de
description: >
  DanceSocially ist die Webseite des Tanztrainers Georg Tavonius mit Informationen
  zum Thema West Coast Swing und Gesellschaftstanzen. Hier erfahrt ihr, wo es Kurse
  oder die nächste Veranstaltung gibt. In Hamburg und in Deutschland.
keywords: >
  West Coast Swing, Hamburg, WCS, tanzen, WCS Unterricht, West Coast Swing lernen,
  West Coast Swing Events, West Coast Swing Workshops, WCS Events, WCS Workshops,
  Was ist West Coast Swing
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.dancesocially.com" # the base hostname & protocol for your site
twitter_username: Georg_Tavonius
github_username:  Calamari
googleplus_url: https://plus.google.com/u/0/100254305021076830105

og_description: West Coast Swing in Hamburg mit Georg Tavonius. Blog, Infos und mehr.

# Facebook app id, so we can clear cache and stuff
fb:
  app_id: 1111600618858744,

menu_entries:
  # -
  #   title: Blog
  #   url: /
  -
    title: Über mich
    url: /ueber-mich/
  -
    title: West Coast Swing
    sub_menu:
      -
        title: Was ist West Coast Swing
        url: /west-coast-swing/
      -
        title: West Coast Swing Unterricht in Hamburg
        url: /wcs-unterricht/
      -
        title: Events und Workshops
        url: /events-workshops/
  -
    title: Zouk
    sub_menu:
      -
        title: Was ist Zouk
        url: /zouk/
      -
        title: Zouk Unterricht in Hamburg
        url: /zouk-unterricht/
      -
        title: Events und Workshops
        url: /zouk-events-workshops/

# Build settings
markdown: kramdown


# event_promo:
#   date: 2016-04-30T10:30+01:00
#   endDate: 2016-05-01T18:00+01:00
#   title: WCS-Intensive mit Eric Jacobson 2016
#   image: www.dancesocially.com/assets/fb-eric-intensive-2.jpg
#   url: www.dancesocially.com/events/eric-intensive-2016/
#   description: Der AllStar Eric Jacobson ist wieder zu Besuch in Hamburg. Für ein weiteres hochklassiges Intensiv-Workshop.
#   location:
#     name: Tanzschule Heiko Stender
#     address: Tibarg 40, 22459 Hamburg
#     url: www.tanzschule-stender.de
#   offers:
#     -
#       name: Anmeldung im Februar
#       price: 110
#     -
#       name: Anmeldung im März
#       price: 120
#     -
#       name: Anmeldung im April
#       price: 130
#   performer:
#     name: Eric B. Jacobson
#     url: www.nakedbasics.com

# event_promo:
#   date: 2016-06-18T18:00+02:00
#   endDate: 2016-06-18T22:00+01:00
#   title: WCS Mid-Week Workshop & Party mit Eric Jacobson
#   image: www.dancesocially.com/assets/fb-eric-intensive-2.jpg
#   url: www.facebook.com/events/181004265631971/
#   description: Eric ist nächste Woche auf durchdreise in Hamburg und da lassen wir es uns nicht nehmen ihn für einen Abend als Trainer für einen Workshop einzuspannen. Julian und Juliane haben sich bereit erklärt ihre üblichen Tanzraum dafür zu Verfügung zu stellen und das Billies erlaubt uns sogar eine Party im Anschluss zu machen.
#   location:
#     name: Billies - Das Tanzstudio in Hamburg
#     address: Stresemannstraße 374, Hamburg
#     url: www.facebook.com/tanzstudio.billies/
#   offers:
#     -
#       name: 1 Workshop (inkl Party)
#       price: 14
#     -
#       name: 2 Workshops (inkl Party)
#       price: 23
#     -
#       name: Party only
#       price: 3
#   performer:
#     name: Eric B. Jacobson
#     url: www.nakedbasics.com

wcs_parties:
  -
    date: 2017-09-02
    title: Anchor Saturday
    url: www.facebook.com/events/229807244169983
    location:
      name: Isabel Edvardsson - Die Tanzschule
      address: Banksstr. 2b, 20097 Hamburg
      url: www.facebook.com/Isabel-Edvardsson-DIE-Tanzschule-725862844157068/
  -
    date: 2017-09-15
    title: West Coast Friday
    url: www.facebook.com/events/1863905547159981
    location:
      name: Isabel Edvardsson - Die Tanzschule
      address: Banksstr. 2b, 20097 Hamburg
      url: www.facebook.com/Isabel-Edvardsson-DIE-Tanzschule-725862844157068/
  -
    date: 2017-10-04
    title: Anchor Saturday
    url: www.julianundjuliane.de/termine/west-coast-swing-partys/
    location:
      name: Isabel Edvardsson - Die Tanzschule
      address: Banksstr. 2b, 20097 Hamburg
      url: www.facebook.com/Isabel-Edvardsson-DIE-Tanzschule-725862844157068/
  -
    date: 2017-01-17
    title: West Coast Friday
    url: www.julianundjuliane.de/termine/west-coast-swing-partys/
    location:
      name: Isabel Edvardsson - Die Tanzschule
      address: Banksstr. 2b, 20097 Hamburg
      url: www.facebook.com/Isabel-Edvardsson-DIE-Tanzschule-725862844157068/

wcs_workshops:
  -
    date: 2017-10-26
    endDate: 2017-10-30
    title: Warsaw Halloween Swing
    url: warsawhalloweenswing.com
    description: Gruseliges WSDC-Registry und Tanz-Event. Es besticht durch eine tolle Atmosphäre, sensationelle Kostüme und gute Workshops.
    location:
      name: The WESTIN Warsaw
      address: Jana Pawla II 21, 00-854 Warsaw, Poland
      url: www.facebook.com/the.westin.warsaw
  -
    date: 2017-11-10
    endDate: 2017-11-12
    title: Red Light Swing
    url: www.redlightswing.com
    description: Hamburgs neustes West Coast Swing Event.

zouk_parties:
  -
    date: 2017-09-09
    title: Go With The Flow
    url: www.facebook.com/events/761993163973916/
    location:
      name: TanzCentrum Gold und Silber Bremen e.V.
      address: Waller Heerstraße 46, 28217 Bremen, Germany
      url: tc-gold-und-silber.de

zouk_workshops:
  -
    date: 2017-09-28
    endDate: 2017-10-01
    title: 4. Zouk/Kizomba Gala in Hannover
    url: www.facebook.com/events/1792200144369871/
    description: Ein Zouk und Kizomba Mix-Event im Norden Deutschlands. Die Hamburger werden da zahlreich vertreten sein.
    location:
      name: Culinar Hannover
      address: Am Grossen Garten 3, 30419 Hannover
      url: www.salsa-culinar.de
  -
    date: 2017-12-08
    endDate: 2017-12-10
    title: Zouk Family Meeting christmas edition
    url: zouk-dresden.de/?q=zfm13
    description: Die Weihnachtsausgabe eines sehr schönes und familiäres Zouk Event in Dresen. Natürlich mit gemeinsamen Weihnachtsmarktbesuch!
    location:
      name: dance studio “Sandana”
      address: Trachenberger Platz 3, 01139 Dresden
      url: www.salsa-sandana.de/startseite/

wcs_workshops_suggestions:
  -
    date: 2017-12-07
    endDate: 2017-12-10
    title: Berlin Swing Revolution
    url: berlinswingrevolution.de/
    description: Die Berlin Swing Revolution geht in die zweite Runde. Diesmal als WSDC-Registry Event.
    location:
      name: ??
      address: ??
      url: berlinswingrevolution.de/
