# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

gems:
- jekyll-assets

assets:
  features:
    liquid: false
  assets:
    - "*.png"
    - "main.css"
  sources:
    - bower_components
    - img

# Site settings
title: DanceSocially
email: georg@get83.de
description: >
  DanceSocially ist die Webseite des Tanztrainers Georg Tavonius mit Informationen
  zum Thema West Coast Swing und Gesellschaftstanzen. Hier erfahrt ihr, wo es Kurse
  oder die nächste Veranstaltung gibt. In Hamburg und in Deutschland.
keywords: >
  West Coast Swing, Hamburg, WCS, tanzen, WCS Unterricht, West Coast Swing lernen,
  West Coast Swing Events, West Coast Swing Workshops, WCS Events, WCS Workshops,
  Was ist West Coast Swing
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.dancesocially.com" # the base hostname & protocol for your site
twitter_username: Georg_Tavonius
github_username:  Calamari
googleplus_url: https://plus.google.com/u/0/100254305021076830105

og_description: West Coast Swing in Hamburg mit Georg Tavonius. Blog, Infos und mehr.

# Facebook app id, so we can clear cache and stuff
fb:
  app_id: 1111600618858744,

menu_entries:
  # -
  #   title: Blog
  #   url: /
  -
    title: Über mich
    url: /ueber-mich/
  -
    title: West Coast Swing
    url: /west-coast-swing/
  -
    title: Unterricht in Hamburg
    url: /wcs-unterricht/
  -
    title: Events und Workshops
    url: /events-workshops/

# Build settings
markdown: kramdown


# event_promo:
#   date: 2016-04-30T10:30+01:00
#   endDate: 2016-05-01T18:00+01:00
#   title: WCS-Intensive mit Eric Jacobson 2016
#   image: www.dancesocially.com/assets/fb-eric-intensive-2.jpg
#   url: www.dancesocially.com/events/eric-intensive-2016/
#   description: Der AllStar Eric Jacobson ist wieder zu Besuch in Hamburg. Für ein weiteres hochklassiges Intensiv-Workshop.
#   location:
#     name: Tanzschule Heiko Stender
#     address: Tibarg 40, 22459 Hamburg
#     url: www.tanzschule-stender.de
#   offers:
#     -
#       name: Anmeldung im Februar
#       price: 110
#     -
#       name: Anmeldung im März
#       price: 120
#     -
#       name: Anmeldung im April
#       price: 130
#   performer:
#     name: Eric B. Jacobson
#     url: www.nakedbasics.com

# event_promo:
#   date: 2016-06-18T18:00+02:00
#   endDate: 2016-06-18T22:00+01:00
#   title: WCS Mid-Week Workshop & Party mit Eric Jacobson
#   image: www.dancesocially.com/assets/fb-eric-intensive-2.jpg
#   url: www.facebook.com/events/181004265631971/
#   description: Eric ist nächste Woche auf durchdreise in Hamburg und da lassen wir es uns nicht nehmen ihn für einen Abend als Trainer für einen Workshop einzuspannen. Julian und Juliane haben sich bereit erklärt ihre üblichen Tanzraum dafür zu Verfügung zu stellen und das Billies erlaubt uns sogar eine Party im Anschluss zu machen.
#   location:
#     name: Billies - Das Tanzstudio in Hamburg
#     address: Stresemannstraße 374, Hamburg
#     url: www.facebook.com/tanzstudio.billies/
#   offers:
#     -
#       name: 1 Workshop (inkl Party)
#       price: 14
#     -
#       name: 2 Workshops (inkl Party)
#       price: 23
#     -
#       name: Party only
#       price: 3
#   performer:
#     name: Eric B. Jacobson
#     url: www.nakedbasics.com

parties:
  -
    date: 2017-08-05
    title: Anchor Saturday
    url: www.facebook.com/events/227211927762774
    location:
      name: Isabel Edvardsson - Die Tanzschule
      address: Banksstr. 2b, 20097 Hamburg
      url: www.facebook.com/Isabel-Edvardsson-DIE-Tanzschule-725862844157068/
  -
    date: 2017-08-18
    title: West Coast Friday
    url: www.facebook.com/events/307130086367657
    location:
      name: Isabel Edvardsson - Die Tanzschule
      address: Banksstr. 2b, 20097 Hamburg
      url: www.facebook.com/Isabel-Edvardsson-DIE-Tanzschule-725862844157068/
  -
    date: 2017-09-02
    title: Anchor Saturday
    url: www.facebook.com/events/229807244169983
    location:
      name: Isabel Edvardsson - Die Tanzschule
      address: Banksstr. 2b, 20097 Hamburg
      url: www.facebook.com/Isabel-Edvardsson-DIE-Tanzschule-725862844157068/
  -
    date: 2017-09-15
    title: West Coast Friday
    url: www.facebook.com/events/1863905547159981
    location:
      name: Isabel Edvardsson - Die Tanzschule
      address: Banksstr. 2b, 20097 Hamburg
      url: www.facebook.com/Isabel-Edvardsson-DIE-Tanzschule-725862844157068/



workshops:
  -
    date: 2017-08-12
    endDate: 2017-08-12
    title: Riga Summer Swing
    url:
    description: Ein WSDC Event im Herzen von Lettland.
    location:
      name:
      address:
      url:
  -
    date: 2017-10-26
    endDate: 2017-10-30
    title: Warsaw Halloween Swing
    url: warsawhalloweenswing.com
    description: Gruseliges WSDC-Registry und Tanz-Event. Es besticht durch eine tolle Atmosphäre, sensationelle Kostüme und gute Workshops.
    location:
      name: The WESTIN Warsaw
      address: Jana Pawla II 21, 00-854 Warsaw, Poland
      url: www.facebook.com/the.westin.warsaw

workshops_suggestions:
  -
    date: 2017-12-07
    endDate: 2017-12-10
    title: Berlin Swing Revolution
    url: berlinswingrevolution.de/
    description: Die Berlin Swing Revolution geht in die zweite Runde. Diesmal als WSDC-Registry Event.
    location:
      name: ??
      address: ??
      url: berlinswingrevolution.de/
