# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DanceSocially
email: georg@get83.de
description: >
  DanceSocially ist die Webseite des Tanztrainers Georg Tavonius mit Informationen
  zum Thema West Coast Swing und Gesellschaftstanzen. Hier erfahrt ihr, wo es Kurse
  oder die nächste Veranstaltung gibt. In Hamburg und in Deutschland.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.dancesocially.com" # the base hostname & protocol for your site
twitter_username: Georg_Tavonius
github_username:  Calamari

og_description: West Coast Swing in Hamburg mit Georg Tavonius. Blog, Infos und mehr.

menu_entries:
  # -
  #   title: Blog
  #   url: /
  -
    title: Über mich
    url: /ueber-mich/
  -
    title: West Coast Swing
    url: /west-coast-swing/
  -
    title: Unterricht in Hamburg
    url: /wcs-unterricht/
  -
    title: Events und Workshops
    url: /events-workshops/

# Build settings
markdown: kramdown

parties:
  # -
  #   day: 19
  #   month: Dez
  #   title: X-Mas Swing Special
  #   url: www.facebook.com/events/1522556231368741
  -
    day: 15
    month: Jan
    title: Anchor Festival
    url: www.julianundjuliane.de/anchorfestival/de/
  -
    day: 16
    month: Jan
    title: Anchor Festival
    url: www.julianundjuliane.de/anchorfestival/de/
  -
    day: 23
    month: Jan
    title: Party @ Dance Your Life
    info: inkl. Schnupperworkshop
    url: www.tanzschule-bergedorf.com/kurse/gesellschaftstanzen/west-coast-swing/
  -
    day: 29
    month: Jan
    title: West Coast Friday
    url: www.julianundjuliane.de/termine/west-coast-swing-partys/
  -
    day: 6
    month: Feb
    title: Anchor Saturday
    url: www.facebook.com/events/881171021999263/
  -
    day: 13
    month: Feb
    title: Party @ Dance Your Life
    url: www.tanzschule-bergedorf.com/kurse/gesellschaftstanzen/west-coast-swing/
  -
    day: 19
    month: Feb
    title: West Coast Friday
    url: www.julianundjuliane.de/termine/west-coast-swing-partys/
  -
    day: 5
    month: Mär
    title: Anchor Saturday
    url: www.facebook.com/events/1967645630127664/
  -
    day: 12
    month: Mär
    title: Party @ Dance Your Life
    url: www.tanzschule-bergedorf.com/kurse/gesellschaftstanzen/west-coast-swing/
  -
    day: 18
    month: Mär
    title: West Coast Friday
    url: www.julianundjuliane.de/termine/west-coast-swing-partys/
  -
    day: 2
    month: Apr
    title: Anchor Saturday
    url: www.facebook.com/events/213113712362499/
  # -
  #   day: 9
  #   month: Apr
  #   title: Party @ Dance Your Life
  #   url: www.tanzschule-bergedorf.com/kurse/gesellschaftstanzen/west-coast-swing/
  # -
  #   day: 22
  #   month: Apr
  #   title: West Coast Friday
  #   url: www.julianundjuliane.de/termine/west-coast-swing-partys/
  # -
  #   day: 7
  #   month: Mai
  #   title: Anchor Saturday
  #   url: www.facebook.com/events/154215528284072/
  # -
  #   day: 14
  #   month: Mai
  #   title: Party @ Dance Your Life
  #   url: www.tanzschule-bergedorf.com/kurse/gesellschaftstanzen/west-coast-swing/
  # -
  #   day: 20
  #   month: Mai
  #   title: West Coast Friday
  #   url: www.julianundjuliane.de/termine/west-coast-swing-partys/
  # -
  #   day: 4
  #   month: Jun
  #   title: Anchor Saturday
  #   url: www.facebook.com/events/204216419925053/
  # -
  #   day: 11
  #   month: Jun
  #   title: Party @ Dance Your Life
  #   url: www.tanzschule-bergedorf.com/kurse/gesellschaftstanzen/west-coast-swing/
  # -
  #   day: 24
  #   month: Jun
  #   title: West Coast Friday
  #   url: www.julianundjuliane.de/termine/west-coast-swing-partys/
  # -
  #   day: 9
  #   month: Jul
  #   title: Party @ Dance Your Life
  #   url: www.tanzschule-bergedorf.com/kurse/gesellschaftstanzen/west-coast-swing/
  # -
  #   day: 13
  #   month: Aug
  #   title: Party @ Dance Your Life
  #   url: www.tanzschule-bergedorf.com/kurse/gesellschaftstanzen/west-coast-swing/
  # -
  #   day: 10
  #   month: Sep
  #   title: Party @ Dance Your Life
  #   url: www.tanzschule-bergedorf.com/kurse/gesellschaftstanzen/west-coast-swing/
  # -
  #   day: 8
  #   month: Okt
  #   title: Party @ Dance Your Life
  #   url: www.tanzschule-bergedorf.com/kurse/gesellschaftstanzen/west-coast-swing/
  # -
  #   day: 12
  #   month: Nov
  #   title: Party @ Dance Your Life
  #   url: www.tanzschule-bergedorf.com/kurse/gesellschaftstanzen/west-coast-swing/
  # -
  #   day: 10
  #   month: Dez
  #   title: Party @ Dance Your Life
  #   url: www.tanzschule-bergedorf.com/kurse/gesellschaftstanzen/west-coast-swing/


workshops:
  # -
  #   day: 19
  #   month: Dez
  #   title: X-Mas Swing Special
  #   url: www.facebook.com/events/1522556231368741
  #   teaching: true
  # -
  #   day: 8-10
  #   month: Jan
  #   title: Budafest
  #   url: www.wcs-budafest.com
  -
    day: 15-17
    month: Jan
    title: Anchor Festival
    url: www.julianundjuliane.de/anchorfestival/de/
    description: Hamburgs großes West Coast Swing Festival.
  -
    day: 5-7
    month: Feb
    title: Swingtzerland
    url: www.swingtzerland.com
    description: Ein kleines aber feines WSDC Registry Event in Zürich.
  -
    day: 13-16
    month: Mai
    title: Swingmany
    url: www.swingmany.de
    description: Deutschlands beste Lehrer unterrichten auf deutsch.
  -
    day: 27-29
    month: Mai
    title: Hungarian Open
    url: wcs-ho.com
    description: Ein schönes ungarisches WSDC Event.
  -
    day: 16-19
    month: Jun
    title: D-Town Swing
    url: d-townswing.com
    description: Das beste Lineup in Deutschland (und vielleicht sogar in Europa).
  -
    day: 3-6
    month: Jun
    title: Intensive mit Brandi Tobias
    url: www.facebook.com/events/1661776737410624
    description: Die brilliante Brandi Tobias gibt ein Intensive hier in Deutschland. Ein muss.
  -
    day: 27-31
    month: Okt
    title: Warsaw Halloween Swing
    url: warsawhalloweenswing.com
    description: Gruseliges WSDC und Tanz-Event. Tolle Atmosphäre und tolle Kostüme.

workshops_suggestions:
  -
    day: 1-3
    month: Jul
    title: NeverlandSwing III
    url: www.facebook.com/profile.php?id=1123632157652382
    description: Ein kleines aber schönes West Coast Swing Event in den Niederlanden.
  -
    day: 22-24
    month: Jul
    title: Jurassic Swing
    url: www.jurassic-swing.com/
    description: Das erste West Coast Swing Event in Deutschland, welches in einem Naturerlebnisparl statt findet.
  -
    day: 9-15
    month: Jul
    title: Westie on the Promenade
    url: westie.balboaonthepromenade.com
    description: Ein reines Social-Event. Eine Woche Strand, Sonne und tanzen, tanzen, tanzen.
  -
    day: 30-6
    month: Aug-Sep
    title: Westie on the Promenade
    url: http://improteam.com/en/ssdc/home
    description: Eine Woche Tanztraining in West Coast Swing und Zouk in Spanien.
  -
    day: 9-11
    month: Okt
    title: West Coast Swing Festival Düsseldorf
    url: www.wcs-festival.de
    description: Der kleine Bruder des D-Town Swings. Aber trotzdem großartige Trainer.
